# Generated by Django 4.2 on 2024-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='slug',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='custom_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='short_key',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
