# Generated by Django 4.2 on 2024-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_shorturl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
